export ETH_INTERFACE=enp2s0
export WIFI_INTERFACE=wlp1s0
export INTERNAL_MONITOR_OUTPUT=eDP1
export EXTERNAL_MONITOR_OUTPUT=HDMI1
export EXTERNAL_MONITOR_LOCATION="--left-of"
export POINTER_DEVICE_ID_TO_SUSPEND=16
