export ETH_INTERFACE=enp0s31f6
export WIFI_INTERFACE=wlp61s0
export INTERNAL_MONITOR_OUTPUT=eDP1
export EXTERNAL_MONITOR_OUTPUT=HDMI2
export EXTERNAL_MONITOR_LOCATION="--right-of"
export POINTER_DEVICE_ID_TO_SUSPEND=15
export CUDA_HOME=/usr/local/cuda-10.1
