[tool.ruff]
lint.select = [ "ALL" ]
respect-gitignore = true
lint.extend-ignore = [
    "S101", # use of assert
    "PLR2004", # Magic value used in comparison, consider replacing 2 with a constant variable
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "PLR0913", # Too many arguments to function call
    "ERA001", # commented out code
    "D", # docstrings
    "ERA001", # commented-out code
    "T201", # print was found
    "ANN", # annotations
    "INP001", # is part of an implicit namespace package.
    "COM812", # Trailing comma missing
    "TD", # TODO stuff
]
target-version = "py310"
