#!/bin/bash

case $BLOCK_BUTTON in
    1) nmcli dev connect "$ETH_INTERFACE" > /dev/null ; sleep 3 ;;
    3) nmcli dev disconnect "$ETH_INTERFACE" > /dev/null ; sleep 1 ;;
esac

STATUS=$(nmcli c show --active | grep ethernet | awk '{ print $1 }')
if [ -z "$STATUS" ]; then
  echo noeth
  exit
fi
echo eth
