#!/usr/bin/env bash
LNG=$(xkblayout-state print %s | awk '{print toupper($0)}')
case $LNG in
  "US")
    CLR=\#00FF00 ;; # green
  "AM")
    CLR=\#FF0000 ;; # red
esac
echo "$LNG"
echo "$LNG"
echo "$CLR"
