#!/usr/bin/env bash
case $BLOCK_BUTTON in
    1) ~/.config/i3/key_layout_switch ;;  # left click, switch
esac
LNG=$(xkblayout-state print %s)
case $LNG in
  "us")
    CLR=\#00FF00 ;; # green
  "am")
    CLR=\#FF0000 ;; # red
esac
echo "$LNG"
echo "$LNG"
echo "$CLR"
