#!/bin/bash

volumepath="$HOME"/.dotfiles/bin/i3-volume.sh
volumestep=5

case $BLOCK_BUTTON in
  3) $volumepath -m ;;
  4) $volumepath -i $volumestep ;;
  5)  $volumepath -d $volumestep ;;
esac

echo $($volumepath -g)
