#!/bin/bash

WIFI_INTERFACE=$(cat /proc/net/wireless | perl -ne '/(\w+):/ && print $1')
if [ -z $WIFI_INTERFACE] || [ "$(cat /sys/class/net/$WIFI_INTERFACE/operstate)" = 'down' ]; then
    echo "wifi"
    echo "wifi"
    echo "#FF0000"
    exit
fi

QUALITY="$(grep $WIFI_INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')"

SSID="$(iw dev ${WIFI_INTERFACE} link | grep SSID | cut -d " " -f 2-)"
echo "wifi: $SSID $QUALITY%"
echo "wifi: $SSID $QUALITY%"

if [[ $QUALITY -ge 80 ]]; then
    echo "#00FF00"
elif [[ $QUALITY -ge 60 ]]; then
    echo "#FFF600"
elif [[ $QUALITY -ge 40 ]]; then
    echo "#FFAE00"
else
    echo "#FF0000"
fi
