#!/bin/bash

case $BLOCK_BUTTON in
    1) nmcli radio wifi on ; sleep 10 ;;
    3) nmcli radio wifi off ; sleep 1 ;;
esac

if [ -z $WIFI_INTERFACE] || [ "$(cat /sys/class/net/$WIFI_INTERFACE/operstate)" != 'up' ]; then
    echo "wifi"
    echo "wifi"
    echo "#af3a03"
    exit
fi

QUALITY="$(grep $WIFI_INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')"

SSID="$(iw dev ${WIFI_INTERFACE} link | grep SSID | cut -d " " -f 2-)"
echo "wifi: $SSID $QUALITY%"
echo "wifi: $SSID $QUALITY%"

if [[ $QUALITY -ge 80 ]]; then
    echo "#79740e"
elif [[ $QUALITY -ge 60 ]]; then
    echo "#b57614"
else
    echo "#af3a03"
fi
